include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_declare_return_types: true
    avoid_empty_else: true
    always_use_package_imports: false
